version: '3'
services:
  web:
    build: ./docker/nginx
    volumes:
      - ./docker/nginx/conf.d:/etc/nginx/conf.d
      - .:/var/www/html
    ports:
      - 80:80
      - 443:443
    restart: always
    depends_on:
      - app
      - db
      - db_test

  app:
    build: ./docker/fpm
    restart: always
    depends_on:
      - db
      - db_test
    env_file:
      - ./.env
    volumes:
      - ./docker/fpm/php.ini:/usr/local/etc/php/conf.d/php.ini
      - ./docker/fpm/xdebug.ini:/usr/local/etc/php/conf.d/xdebug.ini
      - .:/var/www/html

  db:
    image: "postgres:${DB_TAG}"
    restart: always
    env_file:
      - ./.env
    environment:
      - POSTGRES_DB=${DB_DATABASE}
      - POSTGRES_USER=${DB_USERNAME}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
    ports:
      - 54322:${DB_PORT}
    volumes:
      - /private/var/lib/postgresql/data:/var/lib/postgresql/data

  db_test:
    image: "postgres:${TEST_DB_TAG}"
    restart: always
    env_file:
      - ./.env
    environment:
      - POSTGRES_DB=${TEST_DB_DATABASE}
      - POSTGRES_USER=${TEST_DB_USERNAME}
      - POSTGRES_PASSWORD=${TEST_DB_PASSWORD}
    ports:
      - 54323:${TEST_DB_PORT}

  pgadmin4:
    build: docker/pgadmin4
    ports:
      - 5050:80
    environment:
      - PGADMIN_DEFAULT_EMAIL=${PGADMIN_DEFAULT_EMAIL}
      - PGADMIN_DEFAULT_PASSWORD=${PGADMIN_DEFAULT_PASSWORD}
    volumes:
      - /private/var/lib/pgadmin:/var/lib/pgadmin
